services:
  mvlinux:
    image: mdh81/linux-vnc-base
    environment:
      DEV_CONTAINER: "true"
    volumes:
      - ../:/headless/meshviewer
      - ~/.vimrc:/headless/.vimrc
      - ~/.vim:/headless/.vim  
    ports:
      - "6911:6901"
