name: Build & Quality Checks

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mdh81/mvlinux-alpine

    steps:
      - name: docker debug
        run: |          
          /usr/bin/docker inspect grep $(docker ps --format "{{.Names}}\t{{.Image}}" | grep 'mdh81/mvlinux-alpine' | cut -f1)
          /usr/bin/docker ls -a | grep $(docker ps --format "{{.Names}}\t{{.Image}}" | grep 'mdh81/mvlinux-alpine' | cut -f1)
          /usr/bin/docker run --rm -it --entrypoint /bin/sh mdh81/mvlinux-alpine
          /usr/bin/docker logs -f | grep $(docker ps --format "{{.Names}}\t{{.Image}}" | grep 'mdh81/mvlinux-alpine' | cut -f1)
          
      - name: Checkout MeshViewer
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Test
        run: ctest -C Release --rerun-failed --output-on-failure -S /meshviewer/build
