name: Build & Quality Checks

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout MeshViewer
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Create Docker Image
        run: |        
          docker build -t mvlinux -f ${{github.workspace}}/docker/Dockerfile.CICD .

      - name: Create Docker container
          docker run -d --name cicd -v ${{github.workspace}}:/meshviewer mvlinux                

      - name: Configure CMake
        run: docker exec cicd cmake -B /meshviewer/build -DCMAKE_BUILD_TYPE=Release

     # - name: Build
     #   run: cmake --build ${{github.workspace}}/build --config Release

     # - name: Test
     #   run: ctest -C Release --rerun-failed --output-on-failure -S /meshviewer/build
