name: Emscripten Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_run:
    workflows: [ "Build & Quality Checks" ]
    branches: [ "master" ]
    types:
      - completed

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout MeshViewer
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Emscripten
        run: brew install emscripten

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DEMSCRIPTEN=On

      - name: Build
        run: |
          cd ${{github.workspace}}/build 
          make -j4