name: Emscripten Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_run:
    workflows: [ "Build & Quality Checks" ]
    branches: [ "master" ]
    types:
      - completed

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout MeshViewer
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Each step in a job is run independently with its own environment, which requires emsdk environment to be initialized
      # for each step separately. To avoid this hassle, just combine the install, configure and build stages into a single step
      # TODO: Use a docker container with emscripten environment to get a cleaner solution 
      - name: Install Emscripten and Build
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          emcmake cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DEMSCRIPTEN=On      
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
