name: Emscripten Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_run:
    workflows: [ "Build & Quality Checks" ]
    branches: [ "master" ]
    types:
      - completed

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout MeshViewer
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Emscripten and Build
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          echo "EMSDK=$(pwd)" >> $GITHUB_ENV
          echo "EM_CONFIG=${{github.workspace}}/emsdk/.emscripten" >> $GITHUB_ENV
          echo "$(./emsdk construct_env)" >> $GITHUB_ENV

      - name: Configure Emscripten Build
        run: emcmake cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DEMSCRIPTEN=On

      - name: Build With Emscripten Compiler
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
